### ISSUE TITLE
Transcription: only show the letters visible on the object/image 

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [kingsdigitallab/crossreads#11]
Note that we would like a toggle for the researchers to see the more readable version of the text as it can help while annotating.

Comments from Simona:

> - < supplied> – can be on its own or inside a < del>. When `@reason=”lost”`, hide the content. When `@reason=”omitted”`, hide the content. When `@reason=”undefined”`, leave for now, [to be discussed]. The last one is used either when a previous editor saw the text and transcribed it but now it’s too eroded or lost and we can’t verify (`@evidence=”previouseditor”`), or when there is a parallel copy from which we can reconstruct the text (`@evidence=”parallel”`). Either way this text isn’t physically there anymore but I want to check that we want these cases hidden, too.
> - < choice> – if children are < corr> and < sic>, leave the content of < corr>; if children are < orig> and < reg>, leave the content of < orig>.
> - For expansions of abbreviations only display the content of < abbr> and a < g> if there is a symbol in there.
> - < surplus> – display the content
>

**Comment by simonastoyanova** [comment]
@geoffroy-noel-ddh A toggle for the complete text is a very good idea. 
In terms of the different supplied texts, I can confirm that we don't want the content of any supplieds visible in the text which is to be matched with image annotations. Particularly is we have the toggle with the full text.

**Comment by geoffroy-noel-ddh** [comment]
I've implemented the rules described above. If you have examples of corr/sic in the corpus, I'll also test that.

**Comment by simonastoyanova** [comment]
There is a `<choice>` with `<reg>` and `<orig>` in ISic000055. Some of these are being dropped in the tokenisated files but we're working on that.

**Comment by geoffroy-noel-ddh** [comment]
Tested with reg/orig. Closing issue. We can reopen if new cases appear.
