### ISSUE TITLE
Some images are not available through the IIIF server

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [kingsdigitallab/crossreads#28]
For instance inscription [ISic001408](https://kingsdigitallab.github.io/crossreads/annotator.html?obj=http://sicily.classics.ox.ac.uk/inscription/ISic001408&img=ISic001408.jpg) has (a reference in its TEI to an image called ISic001408_tiled.tif)[https://github.com/ISicily/ISicily/blob/a535bdc3d9af0cc7eb8935413e7e0f5c0b377f89/inscriptions/ISic001420.xml#L184]. 

From that reference the annotator generate the URL to the IIIF image API:

https://apheleia.classics.ox.ac.uk/iipsrv/iipsrv.fcgi?IIIF=/inscription_images/ISic001408/ISic001408_tiled.tif/info.json

That request returns an error message "/data//inscription_images/ISic001408/ISic001408_tiled.tif is neither a file nor part of an image sequence".

Compare with inscription ISic001420, [which works well in the annotator](https://kingsdigitallab.github.io/crossreads/annotator.html?obj=http://sicily.classics.ox.ac.uk/inscription/ISic001420&img=ISic001420.jpg):

https://apheleia.classics.ox.ac.uk/iipsrv/iipsrv.fcgi?IIIF=/inscription_images/ISic001420/ISic001420_tiled.tif/info.json

The format of the IIIF request sent by the annotator is:

`https://apheleia.classics.ox.ac.uk/iipsrv/iipsrv.fcgi?IIIF=/inscription_images/{DOCID}/{IMGID}_tiled.tif/info.json`

Where `{DOCID}` is the inscription id and `{IMGID}` is the tif file name referenced in the facsimile element of the TEI file.

Please let us know if the image URLs on the IIIF server follow another scheme or if some image in the first batch have not yet been uploaded.

**Comment by JonPrag** [comment]
Uploaded 1408 which was missing. Let us know if any others have been missed / overlooked.
j

**Comment by geoffroy-noel-ddh** [comment]
Thanks @JonPrag . I think there might still be quite a lot missing from that batch. You can tell which one don't load by going to the annotator:

https://kingsdigitallab.github.io/crossreads/annotator.html?obj=http://sicily.classics.ox.ac.uk/inscription/ISic001408&img=ISic001408.jpg

Then clicking on each inscription one by one in the list on the left.

![image](https://github.com/kingsdigitallab/crossreads/assets/3778106/5b9f6b3b-03e0-4d89-9eff-d159356a70a6)

**Comment by geoffroy-noel-ddh** [comment]
@JonPrag @simonastoyanova Please see the list below of the inscriptions for which the image can't be accessed from the IIIF server.

Not working:

1435
1445
1447
1448
1463
1464
1465
1471
1472
1473
1483
1485
3031
3364
3474
20288
20300
20304
20306
20313
20317
20319
20320
20322
20323
20368
20370
20371
20445
20597
20598
20600

Working:

1408
1420
1439
1474
1478
1481
1488
3107
3363
3375
30002

**Comment by JonPrag** [comment]
They haven't been uploaded, sorry! Hoping @simonastoyanova can do this promptly.
j

**Comment by geoffroy-noel-ddh** [comment]
Hi @simonastoyanova in response to your email, did you have a look at my previous message above showing how the annotator formulate the URL for each image and how to obtain that URL by clicking on the icon? Could you test a few of the samples that don't work to check if the URL conforms to what your IIIF server expects and if not let us know what the actual URL should be?

Thanks

**Comment by simonastoyanova** [comment]
Hi @geoffroy-noel-ddh, yes I had a look and went over all these inscriptions to check both the filenames in the XML files and that I have uploaded all of them on the server. The URLs are as you say. If it works for 1420, I don't understand why it doesn't work for 1435, since they are in the same place, following the same structure:
<img width="322" alt="Screenshot 2023-08-24 at 18 11 40" src="https://github.com/kingsdigitallab/crossreads/assets/4941543/23d64480-57f8-4644-8e71-c68011c43e2a">

I'll keep looking.

**Comment by JonPrag** [comment]
There was no problem on the server end when I uploaded the first missing one on Tuesday; I can't see the missing ones either.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JonPrag** [comment]
And just to note that I have just now uploaded the files for ISic001445 and they do now generate a return to the URL query:
https://apheleia.classics.ox.ac.uk/iipsrv/iipsrv.fcgi?IIIF=/inscription_images/ISic001445/ISic001445_tiled.tif/info.json

so it would appear to be a problem at Simona’s end of some sort.

I can do the rest, but it will take time and play hell with my limited data allowance (I’m on mobile broadband in rural Wales at present…)

j

**Comment by geoffroy-noel-ddh** [comment]
Thanks @JonPrag for checking. That can certainly wait for next week or later when you have a better connection.
