### ISSUE TITLE
Auto-saving annotations before context switch

### ISSUE THREAD

**Issue by njakeman** [kingsdigitallab/crossreads#3]
(Observation)
Unsaved annotations do not persist when switching between Annotator and Definition tab. Although this has not been flagged as a problem, could it interrupt workflow if the user needs to make definition changes?
(Minor)

**Comment by geoffroy-noel-ddh** [comment]
And more generally, unsaved annotations are lost if the user selects another image or object. So the question is whether we want to:
1. auto-save so there's never any loss when switching context
2. show a warning message (i.e. Do you want to save your annotations before leaving this image?)
3. leave it unsaved (we save in the browser session but not github; that's more advanced)

**Comment by njakeman** [comment]
@simonastoyanova - do you have a preference from the options described above, or do you see the problem differently?, i.e. not a problem at all :)

**Comment by simonastoyanova** [comment]
@njakeman  I would prefer option 1. I tend to save before I change context but it's entirely possible to forget to save while picking the descriptors, especially if one discovered the need to add a new descriptor and goes straight to the definitions. Hope that makes sense. Happy to test this a but more before we commit to option 1.

**Comment by geoffroy-noel-ddh** [comment]
That makes sense, and many modern interfaces now auto-save changes by default. The only drawback I can think of is an accidental deletion or change (e.g. fat-finger) as we don't have any undo. Technically all previous states are saved in Github so it is feasible to revert if needed. Integrating undos to the UI would be more complicated.

Just something to be aware of. Although I can think of things we could do to limit/mitigate accidents, with better notification. We can talk about that separately.

**Comment by geoffroy-noel-ddh** [comment]
This is mostly done, to be reviewed.

Annotations saved immediately before clicking another object, image or tab.
Also saved every 10 seconds.

Two things to keep in mind while testing/reviewing this:
1.  This may create a log of commits to github during long annotation sessions; I'll have to verify it doesn't exceeds github API limits
2. Regular automated saving may cause the UI to be less responsive for a very short moment; please report if it is disruptive
