### ISSUE TITLE
Selected features don't save

### ISSUE THREAD

**Issue by simonastoyanova** [kingsdigitallab/crossreads#36]
I have now added the complete Greek alphabet to script Greek 1 and started annotating the Archaic inscriptions. 
In 1408, annotated the alpha and selected the relevant featues of the listed components; saved. Moved on to another letter but went back to check that the features of the alpha were saved. They were not, all tick boxes are empty again.

**Comment by geoffroy-noel-ddh** [comment]
Hi @simonastoyanova that bug should be fixed now.
