### ISSUE TITLE
Strip diacritics from text?

### ISSUE THREAD

**Issue by simonastoyanova** [kingsdigitallab/crossreads#37]
Can we strip all accents and other diacritics from the text field? I've noticed that when a letter has a diacritic, the automatic suggestion of an allograph doesn't work. More importantly, some diacritics are non-combining in Unicode and display in a separate box in the interface. We don't really need them for the linking of text and image, they are only useful in the EpiDoc files, so it's probably easier to just strip them for the annotator.

**Comment by geoffroy-noel-ddh** [comment]
Hi @simonastoyanova can you give me an example of characters with diacritics in the collection?

**Comment by geoffroy-noel-ddh** [comment]
I think I see now: 1408, ο̄
![image](https://github.com/kingsdigitallab/crossreads/assets/3778106/0046c3fa-99b8-4e41-8010-86b6462d1330)

**Comment by geoffroy-noel-ddh** [comment]
Yes there are ways to remove diacritics. I've done that in Python before. I'll how it can be done in Javascript.

**Comment by simonastoyanova** [comment]
Thank you @geoffroy-noel-ddh! Even the ones which display properly are not necessary for the annotator, so I think just strip them all rather trying to sort out the non-combining ones.

![Screenshot 2023-09-07 at 12 15 14](https://github.com/kingsdigitallab/crossreads/assets/4941543/b2e95479-1707-4a0a-832d-8e5422732d40)

Many thanks, that wasn't an issue I thought of in the beginning.

**Comment by geoffroy-noel-ddh** [comment]
I'll try to prioritise the fix because will have an effect on the indexing of the letters in the TEI. For instance after removing ̄  , ς will become the 3rd letter, is it should. At the moment it's the fourth. So some annotations after the removed diacritics would have to manually matched again with the text.
