### ISSUE TITLE
DTS transcription / IIIF image mismatch?

### ISSUE THREAD

**Issue by njakeman** [kingsdigitallab/crossreads#4]
Sample image ISic000007 has annotations, but the Transcription does not match the image. It is not clear how the Allograph has been defined. 

** EDIT ** - I see now that the Allograph was selected from the dropdown as usual, however, it seems as if there should be a constraint so that an Annotation must have a corresponding Allograph in the transcription panel?

**Comment by geoffroy-noel-ddh** [comment]
Yep, we discuss that at the last UI/UX interview.

Here's the idea:
1. if the user selects the letter in the transcription and the allograph selector is empty, the corresponding allograph will be selected automatically (this feature will save editors some time, by not having to select the obvious choice each time)
2. if the transcribed letter and the allograph don't match, a warning message/icon will be shown (e.g. mismatch icon next to allograph selector)

If you have other ideas, feel free to share.

**Comment by njakeman** [comment]
I think you're describing the same behaviour, but just to double check - this is an instance where there is NO selection in the Transcription panel at all rather than an overtly conflicting classification between Transcription and Allograph.

**Comment by geoffroy-noel-ddh** [comment]
@njakeman Can you post a screenshot? (you can paste the text box it will import the image for you)

**Comment by geoffroy-noel-ddh** [comment]
Closed. Constraint is not needed as it's possible to draw box without linking with text (could be done at a later stage). But the color coding should be different. Blue border is bound to a sign in the text. Grey isn't.
