### ISSUE TITLE
Definition table ordering

### ISSUE THREAD

**Issue by njakeman** [kingsdigitallab/crossreads#5]
Definition table - Component not listed alphabetically? 
Perhaps a manual sort is required
(minor)

**Comment by geoffroy-noel-ddh** [comment]
That was also discussed during the UI/UX interview.

Allograph & Components should be listed alphabetically.
But features could be re-ordered so there is some meaningful grouping (e.g. features that are variants of the same thing/component).

**Comment by geoffroy-noel-ddh** [comment]
This will need more experimentation & feedback.
Reordering may be challenging UI/UX wise.
