### ISSUE TITLE
Document locks after refreshing browser

### ISSUE THREAD

**Issue by simonastoyanova** [kingsdigitallab/crossreads#53]
When I add a new component or feature in the definitions tab and switch to the annotation tab to continue with image annotation, the document locks. I have tried refreshing, document is still locked. There was nobody else working on those documents at the time. The lock lifts after some time but while its on I have to pause work on that document. Please advise, @geoffroy-noel-ddh.

**Comment by geoffroy-noel-ddh** [comment]
Hi @simonastoyanova I've released a fix. I'm still working on improving the editorial system & conflict detection (gh-32) to address remaining issues. If you notice anything else let me know.

**Comment by simonastoyanova** [comment]
Understood. I can move this thread to issue https://github.com/kingsdigitallab/crossreads/issues/32 if that would be better? List potential other bugs directly under it? Let me know what you prefer.

**Comment by geoffroy-noel-ddh** [comment]
Bugs related to the locking systems can go under gh-32 until I close the ticket. Thank you. No need to move this thread, I can close it now that its fixed.
