### ISSUE TITLE
Testing characters in search facet but not in definition tab

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [kingsdigitallab/crossreads#55]
> In the list if character for script Latin 1, at the bottom of the list there are a few Greek letters listed, I think a leftover from the testing phase:
> 
> ![Screenshot 2024-04-10 at 11 50 16](https://github.com/kingsdigitallab/crossreads/assets/4941543/9ad007e0-b21b-4215-86de-a176f6e49ecb)
> 
> I don't see them in the list of characters for Latin 1 in the definitions tab. Could you let me know where to look to remove them or should I leave that to you?
> 
> 
> _Originally posted by @simonastoyanova in https://github.com/kingsdigitallab/crossreads/issues/45#issuecomment-2047210739_

**Comment by geoffroy-noel-ddh** [comment]
@simonastoyanova I think that's how the faceting engine works. Greek letters will still appear in the character facets even if they don't belong to the selected script. But their count will be 0 because there is no Δ annotation in the result set when filtering by Latin script.

You can actually test that by:
1. clicking Latin under Script filter
2. clicking Δ
3. untick Latin

=> Now you see Δ with 26 annotation (same count for Greek). 

If it helps I can hide the facet options with a 0 count?

**Comment by simonastoyanova** [comment]
@geoffroy-noel-ddh I see, I tried what you suggested. I think what confused me was that only a the first few letters of the unselected script are visible, so I assumed it was a bug. If both alphabets are visible at all times, we can add a scroll to the Character field? Probably safer than hiding the 0 count which might be a useful indicator even within one script.

**Comment by geoffroy-noel-ddh** [comment]
All facets work in the same way: they list the top 30 options in the result set (by count). You can see the same effect if you look at components while selecting a specific character. Or features if you select a component. It will list top 30 relevant options. If there are less than 30, the remaining will be with 0 count. But in every facet the full list of options is truncated to 30.

I did that initially so the facets aren't too long on the web page. But scrolling or expanding/collapsing facets would allow to show everything. I can try that if you want?

**Comment by simonastoyanova** [comment]
OK, I understand better now. It does make sense and keeps things tidy but I think in our case with all those characters and c-f combinations, a scroll or collapse would be better. I wonder whether we should hide Greek characters when Latin script it selected, though there are some inscriptions with a mixture of languages/scripts, hence my initial preference for a scroll when we have both alphabets visible. Let me think on this for a couple days.

**Comment by simonastoyanova** [comment]
Hi @geoffroy-noel-ddh, I have thought a little more on this and I think we should try hiding the 0-counts in all facets. This will solve the initial confusion, neater than a long scroll for users, and also solves the issue of the C-F list as discussed in https://github.com/kingsdigitallab/crossreads/issues/56.

**Comment by geoffroy-noel-ddh** [comment]
I've now hidden the options with zero count from the facets. Let me know in gh-56 is the sorting needs to be changed or can remain by frequency.

**Comment by simonastoyanova** [comment]
@geoffroy-noel-ddh Related question: the facet for tags lists 'null' for all inscriptions which don't gave a tag. Can you remove this, please? I'm using the tags very sparingly for specifict things, so I only want to see those in the list. Many inscriptions won't have any tags, so the null value doesn't give me any useful information.

**Comment by geoffroy-noel-ddh** [comment]
null option is now hidden, as requested.
