### ISSUE TITLE
Sort C-F search facet by components

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [kingsdigitallab/crossreads#56]
> Another thing but it's not a bug. I'm thinking about the comp-feat list and whether we should order it by component, e.g. all combinations of festures for a crossbar, rather than by frequency of attestation. Not sure how good of an idea this is, need to think and discuss, but do let me know if you have any thoughts on this.
> 
> _Originally posted by @simonastoyanova in https://github.com/kingsdigitallab/crossreads/issues/45#issuecomment-2047210739_
>

**Comment by geoffroy-noel-ddh** [comment]
Related to gh-55.

**Comment by simonastoyanova** [comment]
Of course, that makse sense. I suspect in this case we do want to hide the 0-counts. I'll come back to you on that shortly.

**Comment by simonastoyanova** [comment]
@geoffroy-noel-ddh Thank you for sorting the 0-counts as per https://github.com/kingsdigitallab/crossreads/issues/55. Please sort the C-F list by component, it would be much easier to assess the variation of features if I can see all combinations by component.

**Comment by geoffroy-noel-ddh** [comment]
That's now implemented. 

Note it would be fairly easy for me to show:
* a scrollbar or expand button under each facet (to access more than first 30 options)
* controls under each facet to sort options either by frequency or alphabetically

For an example of that see https://digipal.eu/digipal/search/facets/?_st_repo_city=o&_xp_repo_place=0

![image](https://github.com/kingsdigitallab/crossreads/assets/3778106/20cbfb69-2ded-4c82-91b2-f872bf10a4c1)

**Comment by simonastoyanova** [comment]
@geoffroy-noel-ddh Great, thank you! 
Yes, I think both expanding and sorting functions makse sense. Please go ahead and implement.

**Comment by geoffroy-noel-ddh** [comment]
I've added a +/- icon in the top right corner to collapse/expand a facet. Collapsing to 15 options. Expanding to 100.
You can also click the name & count columns in each facet to sort accordingly. Click again to change the sorting direction (ascending vs descending). These facet settings are preserved across page loads.

![image](https://github.com/user-attachments/assets/e89ab829-328e-43c0-820f-fb04c5ab301b)
