### ISSUE TITLE
Definition table adding new items (column behaviour)

### ISSUE THREAD

**Issue by njakeman** [kingsdigitallab/crossreads#6]
Definition table - Adding new Feature to Component. 
Rightmost column (where the new Feature shows up) does not have checkbox. 
Only when adding another Feature type does the previous Feature become available for selection.

Row behaviour seems normal/as expected)

**Comment by geoffroy-noel-ddh** [comment]
That's a known issue also discovered by Simona. Thanks for reporting it.
