### ISSUE TITLE
Facets for allograph, date and place

### ISSUE THREAD

**Issue by simonastoyanova** [kingsdigitallab/crossreads#68]
Follow-up coming from our meeting today, the idea of having a facet for allographs was suggested, to correspond to the dot system of the data model.

For place and date - that's all in the EpiDoc files and shouldn't be difficult to get. It will be very useful to make them visible without having to wait for the main website configuration. @geoffroy-noel-ddh, let me know when you need me to do some testing or whatever else you need. It will be very useful to make them visible without having to wait for the main website configuration.

**Comment by geoffroy-noel-ddh** [comment]
Hi @simonastoyanova I've added facets for the place, material and execution types. There is also a filter for the date range.

https://kingsdigitallab.github.io/crossreads/search.html?pag=1&ppg=24&daf=-1000&dat=2000

**Comment by simonastoyanova** [comment]
Thank you @geoffroy-noel-ddh, I will test and play around with them. All looks good!
