### ISSUE TITLE
Definition table - able to "select" empty column?

### ISSUE THREAD

**Issue by njakeman** [kingsdigitallab/crossreads#7]
Definition table - Leftmost column on Feature table allows for checkbox tick in blank column, i.e. the the "Add" column. From a user PoV this might seem that you Add and Select at the same time.

**Comment by njakeman** [comment]
I suppose that before tackling this and other issues in the definitions table, we should take into account possible redesign of this format. Personally, I think the matrix is very intuitive, but I think @geoffroy-noel-ddh may have some reservations about the implementation

**Comment by geoffroy-noel-ddh** [comment]
Good point... I can't make major change to this until a designer (@ongtiffany ) does some research and makes some suggestions.

But that may require more time and I don't want to block fixes to the definition screen and delay the release of a working version so small fixes like that should be ok. Something like #8 however could wait as it's more involved.
