### ISSUE TITLE
New user interface to define a typology of (sub)allographs

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [kingsdigitallab/crossreads#75]
New user interface to define a typology of (sub)allographs.

This consists of rules like:

Type1.1 = Script s + Grapheme g + Component c + Features f

Which could be displayed as a table.

The definitions are already in a tabular form in Simona's spreadsheet. We can adapt that format.

This would then allow to automate the assignment of tags. 

And possibly create dynamic typing. That is, the allograph or the type is not applied to an annotation and recorded in the annotation file. Instead it is logically assigned based on the compliance to a rule.

**Comment by simonastoyanova** [comment]
Here is the first stage of this work in the spreadsheet for now: https://docs.google.com/spreadsheets/d/1i2Nfas-h55vESN04L2L-EAML9B0a2dUPeG3fjOYSBZk/

**Comment by geoffroy-noel-ddh** [comment]
Hi @simonastoyanova , I've extended the search and definition screens to let you create types, list them and delete them.

A 'rule' is an association between a subset of your definitions and a variant type. More precisely one Allograph and a list of component x feature pairs associated to a type name.

(An allograph, n x (component, feature)) => Type name

For instance (Latin A, (crossbar, straight), (crossbar, ascending)) => 'type1.1'

You can see (and delete) the rules on a new tab under the Definition screen.

![image](https://github.com/user-attachments/assets/ddee2882-d9c4-4571-b378-d8449e751790)

To create a new rule/association, select the Allograph and desired component x features options under the respective facets. Then scroll to the bottom of the facet list and insert a type name. Confirm by clicking 'save'. The name will disappear from the input box and the rule will appear under the Definitions screen (see above).

![image](https://github.com/user-attachments/assets/1b47feb9-ee98-4a86-ab28-51fce5723f90)

Hope that makes sense. Let me know if you have any question.

If that works as you want, we can then discuss the next steps. How to utilise the rules and types. I have some ideas, but please do share if you have others or better ones.

Some ideas:
* use the types for filtering the search (as an alternative to facets and tags)
* use the types eventually to move your graphs into more specific allographs. E.g. All 'Latin A' type 1.1 could be turned into A.1.1 or whatever you chose to call the variant. This would help us move to proper allographic classification. Since at the moment the allograph names are still generic and closer to graphemes (see our long conversation & action plan on https://github.com/kingsdigitallab/crossreads/issues/64).

**Comment by geoffroy-noel-ddh** [comment]
The reason I made the distinction between rule and type is that, in your typology, the same type name correspond to multiple descriptive patterns (e.g. type1.1 for Latin A (crossbar=straight, crossbar=ascending) and Latin B (bowl=open, bowl=round) ). That distinction helps us to clarify what we mean I think, although the interface simplifies things a bit.

**Comment by simonastoyanova** [comment]
Thank you, @geoffroy-noel-ddh, I'm starting to play with this and it looks very easy to use and useful for sorting. I'll have proper feedback the week after next.
