### ISSUE TITLE
Opening multiple Annotator windows broken

### ISSUE THREAD

**Issue by simonastoyanova** [kingsdigitallab/crossreads#77]
When I want to look at several inscriptions at the same time and open several Annotator windows, here is what I see as of this morning:
![Screenshot 2024-10-01 at 12 27 50](https://github.com/user-attachments/assets/7fb21580-ab48-43d9-970d-f6a352bfbf1a)

The same happens if I go via the Search and select thumbnails to open the full inscription in the Annotator. This is new - is it coming from development work and shall I stop doing it for a few days? Let me know.

**Comment by simonastoyanova** [comment]
@geoffroy-noel-ddh I refreshed the Search and that's also broken now:
![Screenshot 2024-10-01 at 12 32 44](https://github.com/user-attachments/assets/f79ddcff-e674-4d96-8c9d-398c0a574c96)

The Annotator is OK (if it's only the one window) and the Definitions is also OK.

**Comment by geoffroy-noel-ddh** [comment]
That's now fixed, sorry about that.
