### ISSUE TITLE
Improve usability of the facets

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [kingsdigitallab/crossreads#79]
The list of facets on the search page is too long and difficult to navigate.

Comment copied from email (28/10/2024):

> I agree with making the facet list sticky – the stickiness of the bulk edit has improved the workflow immensely and it will be the same with the facet list for sure. In terms of collapsing the facets, I initially thought it would be better to collapse them completely because collapsing to a short list might be a little confusing – I had this issue at first before Geoffroy added the count and name sorting when I wasn’t sure why the facet was showing me a short list of particular values.
> 
> I wonder whether we can keep the first facet, the Script, as it is, since for our project it will only ever have two values and it doesn’t make much sense to collapse it.
>
> Just a quick note re the script/language – we do have inscriptions with mixed language, I’d rather not remove the generalisation completely. That facet is tiny in terms of real estate and I don’t think it will be in my way.

**Comment by simonastoyanova** [comment]
Another thing occurred to me - when all facets are collapsable, I'll need to know which ones I have selected from. Can we make the colour of a facet darker when I have picked a value from it? And leave the colour as is when I have not picked a value from a facet? Hope this makes sense! Let me know what you think, there might be a better design way to signify which facets have been picked.

**Comment by geoffroy-noel-ddh** [comment]
Hello! Common practice with faceted search is to list the selected filters/options at the top of the page to remind the user and let them toggle them off selectively. Another idea would be to ensure that a facet is never collapsed if there's a selected option under it. Unless you see a use case for collapsing a facet with selected option?

**Comment by geoffroy-noel-ddh** [comment]
I've made the facets list more compact.

* Collapsing is done by clicking on the facet header (or arrow in front).
* When a facet is collapsed only the header will be shown
* Facet headers less bulky
* Cannot collapse a facet if it contains selected options
* When expanded a facet will show all options found in the results set. But that list is now scrollable. Up to 20 options at any time on screen; this can be adjusted if needed
* as before, whether a facet is collapsed or not is saved in the browser session (rather than the query string). That setting is applied each time the search page is loaded and is therefore browser specific.
