### ISSUE TITLE
Script creation duplicate names

### ISSUE THREAD

**Issue by njakeman** [kingsdigitallab/crossreads#8]
Script creation names new Script as per name in Script dropdown. Would be preferable to add as 'New Script' + increment?

**Comment by geoffroy-noel-ddh** [comment]
That Script bar is quite poor in terms of UI/UX. I did it quickly to have something working but other issues have been found by partners. Suggestions from designers (@ongtiffany @ginestra ) about good UI/UX patterns would be very valuable.

![image](https://user-images.githubusercontent.com/3778106/218743304-dc51cd96-a5e9-411a-bd12-1dc7db875921.png)
