### ISSUE TITLE
Facet item with multiple values

### ISSUE THREAD

**Issue by simonastoyanova** [kingsdigitallab/crossreads#81]
Two cases, one in Execution, one in Place name. Both need splitting but for different reasons.

1. Multiple values in Execution
XML: `layoutDesc/layout/rs[@ana]` where `@ana` has a dotted value, e.g. '#execution.engraved' which points to the taxonomy file https://github.com/ISicily/ISicily/blob/master/alists/ISicily-taxonomies.xml; when there are two execution values we deliberately keep them in separate rs elements: 

![Screenshot 2024-11-13 at 16 06 46](https://github.com/user-attachments/assets/830778ce-4878-4ec3-8455-44c5ac37ba64)

In this case the two execution types are complimentary - the text was first engraved and then rubricated.

Example files: http://sicily.classics.ox.ac.uk/inscription/ISic001132, http://sicily.classics.ox.ac.uk/inscription/ISic000107.

2. Multiple values in Place name
XML: `origPlace/placeName[@type='ancient']` more than once. Rare but happens.

![Screenshot 2024-11-13 at 16 24 54](https://github.com/user-attachments/assets/ee44e2e9-30a1-48f6-a73d-17f0e3682faf)

In this case the two places are alternatives, both have `@cert='low'` as we can't tell which one is more likely.

Example files: http://sicily.classics.ox.ac.uk/inscription/ISic020600

**Comment by geoffroy-noel-ddh** [comment]
The search can now deal properly with multiple values in places of origin and execution types files.
