### ISSUE TITLE
Overlapping annotations suggestion

### ISSUE THREAD

**Issue by njakeman** [kingsdigitallab/crossreads#9]
Usability suggestion - when selecting overlapping Annotations - a common method in vector editing software is to hold down a modifier key (e.g. ALT) while clicking in order to cycle through all objects in the same 2D space.

The selection difficulty is reported by partner in Session II, however, I did not experience it myself, when selecting via a corner outside of current selection. If an annotation exists _entirely_ _within_ another annotation, this may be a problem, but I expect this is unlikely for Latin. 

Future-proofing for pictographic scripts this might be needed?

**Comment by geoffroy-noel-ddh** [comment]
Thanks for the idea @njakeman I didn't know about this convention.

One alternative (or complementary) suggestion I made previously is that "z-index" of annotation could be based on their top-left corner. It's a very simple algorithm we applied to Archetype that worked surprisingly well in most cases. Basically the annotations more to the right and more to the bottom will take precedence when you click. That way a small box within a bigger box will always be clickable.

**Comment by njakeman** [comment]
That's a pretty clever solution @geoffroy-noel-ddh!

**Comment by simonastoyanova** [comment]
@njakeman There are cases of one letter completely inside another in Latin but @geoffroy-noel-ddh's selection solution worked well on the annotations I tried. Will report further if I come across something which isn't covered by this.

**Comment by simonastoyanova** [comment]
Working well for me, I think we can close this.
